# Grabs VS Code's devcontainer base image for Ubuntu 22.04
FROM mcr.microsoft.com/vscode/devcontainers/base:dev-ubuntu-22.04

# Copy library scripts to execute
COPY overlay/ /tmp/overlay/

# Make all overlay scripts executable
RUN chmod +x /tmp/overlay/*.sh

# Install necessary ubuntu package dependencies
RUN /tmp/overlay/install-packages.sh